/*
 * this is auto generated code, please do not modify
 * generated by codegen.exe
 */

#include "insigne/generated_code/oglapis.h"

namespace insigne {

glActiveTexture_t glActiveTexture;

glAttachShader_t glAttachShader;

glBindBuffer_t glBindBuffer;

glBindFramebuffer_t glBindFramebuffer;

glBindRenderbuffer_t glBindRenderbuffer;

glBindTexture_t glBindTexture;

glBindVertexArray_t glBindVertexArray;

glBlendEquation_t glBlendEquation;

glBlendFunc_t glBlendFunc;

glBlitFramebuffer_t glBlitFramebuffer;

glBufferData_t glBufferData;

glCheckFramebufferStatus_t glCheckFramebufferStatus;

glClear_t glClear;

glClearColor_t glClearColor;

glCompileShader_t glCompileShader;

glCreateProgram_t glCreateProgram;

glCreateShader_t glCreateShader;

glCullFace_t glCullFace;

glDeleteBuffers_t glDeleteBuffers;

glDeleteShader_t glDeleteShader;

glDeleteVertexArrays_t glDeleteVertexArrays;

glDepthFunc_t glDepthFunc;

glDepthMask_t glDepthMask;

glDisable_t glDisable;

glDrawBuffers_t glDrawBuffers;

glDrawElements_t glDrawElements;

glEnable_t glEnable;

glEnableVertexAttribArray_t glEnableVertexAttribArray;

glFramebufferRenderbuffer_t glFramebufferRenderbuffer;

glFramebufferTexture2D_t glFramebufferTexture2D;

glFrontFace_t glFrontFace;

glGenBuffers_t glGenBuffers;

glGenFramebuffers_t glGenFramebuffers;

glGenRenderbuffers_t glGenRenderbuffers;

glGenTextures_t glGenTextures;

glGenVertexArrays_t glGenVertexArrays;

glGenerateMipmap_t glGenerateMipmap;

glGetAttribLocation_t glGetAttribLocation;

glGetError_t glGetError;

glGetIntegerv_t glGetIntegerv;

glGetShaderInfoLog_t glGetShaderInfoLog;

glGetShaderiv_t glGetShaderiv;

glGetString_t glGetString;

glGetUniformLocation_t glGetUniformLocation;

glLinkProgram_t glLinkProgram;

glPixelStorei_t glPixelStorei;

glRenderbufferStorage_t glRenderbufferStorage;

glRenderbufferStorageMultisample_t glRenderbufferStorageMultisample;

glScissor_t glScissor;

glShaderSource_t glShaderSource;

glStencilFunc_t glStencilFunc;

glStencilOp_t glStencilOp;

glTexImage2D_t glTexImage2D;

glTexParameteri_t glTexParameteri;

glUniform1f_t glUniform1f;

glUniform1i_t glUniform1i;

glUniform3fv_t glUniform3fv;

glUniformMatrix4fv_t glUniformMatrix4fv;

glUseProgram_t glUseProgram;

glVertexAttribPointer_t glVertexAttribPointer;

glViewport_t glViewport;

}
