/*
 * this is auto generated code, please do not modify
 * generated by codegen.exe
 */

#include "insigne/generated_code/oglapis.h"

namespace insigne {

glActiveTexture_t glActiveTexture;

glAttachShader_t glAttachShader;

glBindBuffer_t glBindBuffer;

glBindBufferBase_t glBindBufferBase;

glBindBufferRange_t glBindBufferRange;

glBindFramebuffer_t glBindFramebuffer;

glBindRenderbuffer_t glBindRenderbuffer;

glBindTexture_t glBindTexture;

glBindVertexArray_t glBindVertexArray;

glBlendEquation_t glBlendEquation;

glBlendFunc_t glBlendFunc;

glBlitFramebuffer_t glBlitFramebuffer;

glBufferData_t glBufferData;

glBufferSubData_t glBufferSubData;

glCheckFramebufferStatus_t glCheckFramebufferStatus;

glClear_t glClear;

glClearColor_t glClearColor;

glClearDepthf_t glClearDepthf;

glColorMask_t glColorMask;

glCompileShader_t glCompileShader;

glCreateProgram_t glCreateProgram;

glCreateShader_t glCreateShader;

glCullFace_t glCullFace;

glDeleteBuffers_t glDeleteBuffers;

glDeleteProgram_t glDeleteProgram;

glDeleteShader_t glDeleteShader;

glDeleteVertexArrays_t glDeleteVertexArrays;

glDeleteFramebuffers_t glDeleteFramebuffers;

glDeleteTextures_t glDeleteTextures;

glDepthFunc_t glDepthFunc;

glDepthMask_t glDepthMask;

glDisable_t glDisable;

glDrawBuffers_t glDrawBuffers;

glDrawElements_t glDrawElements;

glEnable_t glEnable;

glEnableVertexAttribArray_t glEnableVertexAttribArray;

glFramebufferRenderbuffer_t glFramebufferRenderbuffer;

glFramebufferTexture2D_t glFramebufferTexture2D;

glFrontFace_t glFrontFace;

glGenBuffers_t glGenBuffers;

glGenFramebuffers_t glGenFramebuffers;

glGenRenderbuffers_t glGenRenderbuffers;

glGenTextures_t glGenTextures;

glGenVertexArrays_t glGenVertexArrays;

glGenerateMipmap_t glGenerateMipmap;

glGetAttribLocation_t glGetAttribLocation;

glGetError_t glGetError;

glGetIntegerv_t glGetIntegerv;

glGetShaderInfoLog_t glGetShaderInfoLog;

glGetShaderiv_t glGetShaderiv;

glGetString_t glGetString;

glGetStringi_t glGetStringi;

glGetUniformBlockIndex_t glGetUniformBlockIndex;

glGetUniformLocation_t glGetUniformLocation;

glLinkProgram_t glLinkProgram;

glPixelStorei_t glPixelStorei;

glPolygonMode_t glPolygonMode;

glReadBuffer_t glReadBuffer;

glReadPixels_t glReadPixels;

glRenderbufferStorage_t glRenderbufferStorage;

glRenderbufferStorageMultisample_t glRenderbufferStorageMultisample;

glScissor_t glScissor;

glShaderSource_t glShaderSource;

glStencilFunc_t glStencilFunc;

glStencilOp_t glStencilOp;

glTexImage2D_t glTexImage2D;

glTexParameteri_t glTexParameteri;

glTexStorage2D_t glTexStorage2D;

glUniform1f_t glUniform1f;

glUniform1i_t glUniform1i;

glUniform3fv_t glUniform3fv;

glUniformBlockBinding_t glUniformBlockBinding;

glUniformMatrix4fv_t glUniformMatrix4fv;

glUseProgram_t glUseProgram;

glVertexAttribPointer_t glVertexAttribPointer;

glViewport_t glViewport;

glDisableVertexAttribArray_t glDisableVertexAttribArray;

glFinish_t glFinish;

glCompressedTexImage2D_t glCompressedTexImage2D;

glGetProgramiv_t glGetProgramiv;

glGetProgramInfoLog_t glGetProgramInfoLog;

}
