/*
 * this is auto generated code, please do not modify
 * generated by codegen.exe
 */


API_HELPER(void, ActiveTexture);

API_HELPER(void, ClearDepthf);

API_HELPER(void, ColorMask);

API_HELPER(void, AttachShader);

API_HELPER(void, BindBuffer);

API_HELPER(void, BindFramebuffer);

API_HELPER(void, BindRenderbuffer);

API_HELPER(void, BindTexture);

API_HELPER(void, BindVertexArray);

API_HELPER(void, BlendEquation);

API_HELPER(void, BlendFunc);

API_HELPER(void, BlitFramebuffer);

API_HELPER(void, BufferData);

API_HELPER(void, BufferSubData);

API_HELPER(GLenum, CheckFramebufferStatus);

API_HELPER(void, Clear);

API_HELPER(void, ClearColor);

API_HELPER(void, CompileShader);

API_HELPER(GLuint, CreateProgram);

API_HELPER(GLuint, CreateShader);

API_HELPER(void, CullFace);

API_HELPER(void, DeleteBuffers);

API_HELPER(void, DeleteShader);

API_HELPER(void, DeleteVertexArrays);

API_HELPER(void, DepthFunc);

API_HELPER(void, DepthMask);

API_HELPER(void, Disable);

API_HELPER(void, DrawBuffers);

API_HELPER(void, DrawElements);

API_HELPER(void, Enable);

API_HELPER(void, EnableVertexAttribArray);

API_HELPER(void, FramebufferRenderbuffer);

API_HELPER(void, FramebufferTexture2D);

API_HELPER(void, FrontFace);

API_HELPER(void, GenBuffers);

API_HELPER(void, GenFramebuffers);

API_HELPER(void, GenRenderbuffers);

API_HELPER(void, GenTextures);

API_HELPER(void, GenVertexArrays);

API_HELPER(void, GenerateMipmap);

API_HELPER(GLint, GetAttribLocation);

API_HELPER(GLenum, GetError);

API_HELPER(void, GetIntegerv);

API_HELPER(void, GetShaderInfoLog);

API_HELPER(void, GetShaderiv);

API_HELPER(const GLubyte*, GetString);

API_HELPER(const GLubyte*, GetStringi);

API_HELPER(GLint, GetUniformLocation);

API_HELPER(void, LinkProgram);

API_HELPER(void, PixelStorei);

API_HELPER(void, RenderbufferStorage);

API_HELPER(void, RenderbufferStorageMultisample);

API_HELPER(void, Scissor);

API_HELPER(void, ShaderSource);

API_HELPER(void, StencilFunc);

API_HELPER(void, StencilOp);

API_HELPER(void, TexImage2D);

API_HELPER(void, TexStorage2D);

API_HELPER(void, TexParameteri);

API_HELPER(void, Uniform1f);

API_HELPER(void, Uniform1i);

API_HELPER(void, Uniform3fv);

API_HELPER(void, UniformMatrix4fv);

API_HELPER(void, UseProgram);

API_HELPER(void, VertexAttribPointer);

API_HELPER(void, Viewport);

API_HELPER(GLuint, GetUniformBlockIndex);

API_HELPER(void, BindBufferBase);

API_HELPER(void, BindBufferRange);

API_HELPER(void, UniformBlockBinding);

API_HELPER(void, ReadPixels);

API_HELPER(void, ReadBuffer);

API_HELPER(void, PolygonMode);

